version: '2'

services:
    db:
        image: mysql:5.7.16
#port binding is needed to populate it with command line
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: api_doc
            MYSQL_USER: root
    api-doc:
        build: .
        image: api-doc-server:1.0
#        ports:
#            - 3000:3000
        depends_on:
            - db
        environment:
            NODE_ENV: production
    nginx:
        image: nginx
        volumes:
            - "./api-doc.conf:/etc/nginx/conf.d/api-doc.conf"
        ports:
            - 80:80
        depends_on:
            - api-doc
        environment:
            - NGINX_HOST=apidoc.com
            - NGINX_PORT=80
        command: /bin/bash -c "rm /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
