version: '2'

services:
    db:
        image: mysql:5.7.16
        ports:
            - 3306:3306
        volumes:
            - "~/workspace/api_doc/.data/db:/var/lib/mysql"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: api_doc
            MYSQL_USER: root
    api-doc:
        build: .
        image: api-doc-server:1.0
        ports:
            - 3000:3000
        depends_on:
            - db
        environment:
            NODE_ENV: production
