FROM node:7.2.1-wheezy

RUN apt-get -qq update
RUN apt-get install -yq nginx

#copy and launch code
RUN mkdir -p /usr/share/nginx/api-doc/public
ADD public /usr/share/nginx/api-doc/public
RUN mkdir -p /usr/share/nginx/api-doc/config
ADD config /usr/share/nginx/api-doc/config
RUN mkdir -p /usr/share/nginx/api-doc/server
ADD server /usr/share/nginx/api-doc/server
ADD server.js /usr/share/nginx/api-doc
ADD .babelrc /usr/share/nginx/api-doc
ADD README.md /usr/share/nginx/api-doc
ADD package.json /usr/share/nginx/api-doc
RUN npm install /usr/share/nginx/api-doc

CMD tail -f /dev/null


EXPOSE 80
